### ISSUE TITLE
A place to for Pinax discussions

### ISSUE THREAD

**Issue by Postroutine** [pinax/pinax#132]
Exist-it a place liberty-friendly to talk about Pinax?
Because Slack is not this kind of place.

**Comment by paltman** [comment]
What about Slack infringes on liberty?

**Comment by Postroutine** [comment]
Slack is a proprietary service. Like Skype or Whatsapp.

**Comment by paltman** [comment]
Sure. I understand that but don’t see how prosperity and liberty are at odds. How does it affect ones liberty to use a proprietary service when 1) using it is voluntary, 2) there is no fee or transaction required to use it?

**Comment by paltman** [comment]
You are not obligated to use Slack.  Though we'd love to have you join our close 800 member community there, you can always ask questions in issues like you did here, of if it's about a specific project, on a new issue in the respective repository.  However, it does seem to contradict your stance of wanting to avoid proprietary software by making use of Github.

**Comment by Postroutine** [comment]
I use Github only when I don't have choice. Which is already enough.
However, a part of Github are based on GIT, which is ok.

**Comment by paltman** [comment]
Sorry, I meant to say `proprietary` not `prosperity`.

Either way, I wanted to close this thread by saying our two avenues for discussion presently are Slack and Github.  As you may know, running successful open source projects is a lot of work and Pinax is comprised over 60 projects with only a small team of active maintainers.  At this point, maintaining any additional channels of communication would just be too burdensome.

We may at some point in the future add Slack/IRC integration.  I haven't had the time to look into it but I think there is a two way bridge available so that people opposed visiting Slack on the web (you don't have to download a Slack client), will be able to access our chat channels via IRC.  If and when we do this we'll announce it on our [blog](http://blog.pinaxproject.com).

Thanks and best wishes.
