### ISSUE TITLE
drop support for python 2.7.x and django 1.11.x

### ISSUE THREAD

**Issue by mjhea0** [pinax/pinax#146]
With the new LTS release of Django 2.2., can Pinax drop support of Django 1.11.x and Python 2.7.x?

https://docs.djangoproject.com/en/2.2/releases/2.2/

In fact, Django will stop supporting 1.11 at the end of April 2020. That's 1 year to transition over all Pinax projects.

**Comment by mjhea0** [comment]
Along with dropping Python 2 and Django 1, can Pinax add support for https://github.com/ambv/black?

**Comment by KatherineMichel** [comment]
I've started a wiki page about this: https://github.com/pinax/pinax/wiki/Pinax-18.04-Proposed-Process

**Comment by KatherineMichel** [comment]
A few updates that I will add to the wiki page. @jezdez, one of the early Pinax contributors and I chatted at PyCon about Pinax. He suggested that Pinax support the versions of Pinax/Django that are officially supported. As far as Black goes, Django Technical Board has [adopted Black as Django's official formatter](https://twitter.com/andrewgodwin/status/1127027840296177666), to happen when Black hits a stable release. So, in my mind, it makes even more sense to use Black...? Interestingly, Pinax and Black both default to double, not single quotes. I also came away from PyCon with info that [detox has been merged into tox](https://github.com/pinax/pinax/issues/143), an update that can become part of the next release. I've mentioned [switching to Twine](https://github.com/pinax/pinax/issues/144), a newer best practice recommended by the Python Packaging Authority. A [PyCon talk](https://www.youtube.com/watch?v=P3dY3uDmnkU) by @crwilcox also renewed my interest in auto-publishing packages using CircleCI ([example project](https://github.com/crwilcox/my-pypi-package)). I believe @paltman has mentioned in the past setting up auto-publishing based on [this article](https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/). I am doing some research to see what other config improvements and best practices we can incorporate into the release process.

**Comment by mjhea0** [comment]
I like the idea of setting up auto-publishing on Circle. I can help with that if you'd like to open up a new issue.

In terms of the Python/Django support - Since Python 2 will not be supported after 2019, can Pinax start that transition now? I imagine it will take at least 6 months for this due to the number of Pinax projects.

**Comment by KatherineMichel** [comment]
@mjhea0 I think it can start at anytime. But ideally, as much of the process is decided in advance as possible, because there are so many apps/projects. If we change our approach mid-stream, it can create a lot of additional work. We use a spreadsheet to help keep track of the work as its being done.

**Comment by KatherineMichel** [comment]
FYI @mjhea0 or anyone who is interested, I have a [Pinax 19.xx Candidate App Readiness Spreadsheet](https://docs.google.com/spreadsheets/d/1NObVcMzwB5TaGXuSMMQE0vpgEq63WyLApsVk3kR5wiE/edit?usp=sharing) in process. It is more detailed than in the past, because I am trying to eliminate variations between repos (files that do or don't exist, variations in the approach, etc.). I've also got some historical release info in a [Historical Release Links Wiki](https://github.com/pinax/pinax/wiki/Historical-Release-Links) that I will add more to soon (mainly blog posts that explain process).

**Comment by KatherineMichel** [comment]
Closing this issue. Pinax 20.XX release is wrapping up, which drops Python 2.7 and Django 1.11 support. Most of the included apps are tagged and published. Black was not implemented yet, but I will include that in next release plan: https://github.com/pinax/pinax/wiki
