### ISSUE TITLE
Proposal for Pinax Commit Dashboard

### ISSUE THREAD

**Issue by ossanna16** [pinax/pinax#85]
The dashboard should include:
- combined view of issues across projects
- commit stream across projects
- repo organization
- contributor highlights (who is active on what projects?)
- pull request aging
- issue aging
- comment stream (show commit comments, issue comments, pull request comments, all in a single stream)
- labelling of issues, including skill/expertise level (beginner friendly, intermediate, advanced)

**Comment by paltman** [comment]
It is very hard to stay on top of being as responsive as we'd like when there are 60+ repos full of issues and pull requests. Yes, some are more active than others, but all issues and pull requests should receive the same level of attention and response.

We can do better but need some tooling to help things not fall between the cracks.

Part of helping us being responsive, I propose we track different metrics of responsiveness and publicly display them.  In addition, displaying metrics over time will be useful in seeing how we are improving.

I envision the landing page being aggregate metrics with one or two levels of drill down (e.g. click on the "# of open issues without a response" metric to see a list of issues across all of Pinax that you can then easily click on to go see the details on GitHub).

Metrics worth tracking (as a strawman proposal):

#### Point in Time

* # of issues without a response
* # of pull requests without a response
* # of issues needing a response (as determined by it's open and last response was by someone other people who have direct push rights, or maybe better, by the original poster)
* # of pull requests needing a response
* # of open issues
* # of open pull requests

##### Vanity Metrics (because why not)

* # of total stars
* # of total watchers

#### Interval

* # of issues closed in past 30 days
* # of pull requests merged in past 30 days
* # of issues opened in past 30 days
* # of pull requests received in past 30 days
* # of contributors in past 30 days


These can be a grid of decent sized divs to be "stat boxes" of a sort.

Then we can also reveal a time-series graph showing how these metrics have performed on a monthly basis over the past 12-24 months, by clicking on each stat box.  Clicking on a details link for any stat box dealing with issues or pull requests should show a table listing those issues or pull requests with GitHub links to their details.

We could host this dashboard at something like http://dashboard.pinaxproject.com/

**Comment by paltman** [comment]
That was just the contents from #100 so it could merge the dupe.

**Comment by paltman** [comment]
I think we can make this simply as a static site using public GitHub APIs + React + Bootstrap, hosted on GitHub with a CNAME.

**Comment by ossanna16** [comment]
What do you think about adding some functionality which would let people sort issues by badges (First-Timers-Only, Easy Pickings) throughout all Pinax repos so it's easier for them to pick out something they want to work on according to their level of Django/Python expertise? Of course this would require that someone already took a look at the issue and assigned a badge to it first but I think it might be quite useful.

**Comment by paltman** [comment]
@ossanna16 :+1:

**Comment by KatherineMichel** [comment]
This was moved to its own repo. Closing issue. See: https://github.com/pinax/dashboard.pinaxproject.com
